<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ProductsWebAPITest</AssemblyName>
    <IsCodedUITest>False</IsCodedUITest>
    <ReferencePath>$(ProgramFiles)\Common Files\microsoft shared\VSTT\$(VisualStudioVersion)\UITestExtensionPackages</ReferencePath>
    <RootNamespace>ProductsWebAPITest</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
    <TestProjectType>UnitTest</TestProjectType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest.TestFramework" Version="*" />
    <PackageReference Include="MSTest.TestAdapter" Version="*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="*" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
    <PackageReference Include="System.Memory" Version="4.5.5" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Castle.Core" Version="5.1.1" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.0" />
    <PackageReference Include="System.Buffers" Version="4.6.0" />
    <PackageReference Include="System.Numerics.Vectors" Version="4.6.0" />
    <PackageReference Include="Newtonsoft.Json.Bson" Version="1.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../ProductsWebAPI/ProductsWebAPI.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="app.config" />
    <None Include="packages.config" />
  </ItemGroup>
</Project>